resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/fyinnit/flight-school
    branch: master

- name: flight-school-fy
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: fei.ye@innit.com
    password: Feye11!!
    organization: fyinnit.org
    space: development

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
  - put: flight-school-fy
    params:
      manifest: flight-school/manifest.yml